// pages/home1/home1.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    arr:[
      {
        id:1,
        title:'小学',
        img:"../../images/12.jpg",
        type:["全部","三年级上册","三年级下册","四年级上册","四年级下册","五年级上册","五年级下册","六年级上册","六年级下册","专题课程"],
        product:[
          {
            id:11,
            title:"外研版(3起点)同步课堂(三上)",
            grade:"3年级上册",
            type:"三年级上册",
            number:"共18期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/21/dtmw4J.jpg"
          },
          {
            id:12,
            title:"冀教版(3起点)同步课堂(三上)",
            grade:"3年级上册",
            type:"三年级上册",
            number:"共19期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtKKAO.jpg"
          },
          {
            id:13,
            title:"沪教版(3起点)同步课堂(三上)",
            grade:"3年级上册",
            type:"三年级上册",
            number:"共21期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtKgbV.jpg"
          },
          {
            id:14,
            title:"北师大版(3起点)同步课堂(三上)",
            grade:"3年级上册",
            type:"三年级上册",
            number:"共16期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtM9KI.jpg"
          },
          {
            id:15,
            title:"译林版(3起点)同步课堂(三上)",
            grade:"3年级上册",
            type:"三年级上册",
            number:"共18期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtMuMn.jpg"
          },
          {
            id:16,
            title:"北师大版(1起点)同步课堂(三上)",
            grade:"3年级上册",
            type:"三年级上册",
            number:"共14期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt3PSg.jpg"
          },
          {
            id:17,
            title:"北京课改版(1起点)同步课堂(三上)",
            grade:"3年级上册",
            type:"三年级上册",
            number:"共17期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt3f1g.jpg"
          },
          {
            id:18,
            title:"鲁科版(3起点)同步课堂(三上)",
            grade:"3年级上册",
            type:"三年级上册",
            number:"共22期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt3qhT.jpg"
          },
          {
            id:19,
            title:"人教版PEP(三下)同步课堂",
            grade:"3年级下册",
            type:"三年级下册",
            number:"共24期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/21/dt8BCT.jpg"
          },
          {
            id:20,
            title:"外研版(3起点)同步课堂(三下)",
            grade:"3年级下册",
            type:"三年级下册",
            number:"共21期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt8tDs.jpg"
          },
          {
            id:21,
            title:"北师大版(3起点)同步课堂(三下)",
            grade:"3年级下册",
            type:"三年级下册",
            number:"共14期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt8dU0.jpg"
          },
          {
            id:22,
            title:"译林版(3起点)同步课堂(三下)",
            grade:"3年级下册",
            type:"三年级下册",
            number:"共13期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt8Nbn.jpg"
          },
          {
            id:23,
            title:"北师大版(3起点)同步课堂(三下)",
            grade:"3年级下册",
            type:"三年级下册",
            number:"共8期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt8aEq.jpg"
          },
          {
            id:24,
            title:"北京课改版(1起点)同步课堂(三下)",
            grade:"3年级下册",
            type:"三年级下册",
            number:"共21期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt8w5V.jpg"
          },
          {
            id:25,
            title:"沪教版(3起点)同步课堂(三下)",
            grade:"3年级下册",
            type:"三年级下册",
            number:"共26期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt8r2F.jpg"
          },
          {
            id:26,
            title:"冀教版(3起点)同步课堂(三下)",
            grade:"3年级下册",
            type:"三年级下册",
            number:"共26期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt8sv4.jpg"
          },
          {
            id:27,
            title:"鲁科版(3起点)同步课堂(三下)",
            grade:"3年级下册",
            type:"三年级下册",
            number:"共24期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dt8D8U.jpg"
          },
          {
            id:28,
            title:"外研版(3起点)同步课堂(四上)",
            grade:"4年级上册",
            type:"四年级上册",
            number:"共15期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dttAII.jpg"
          },
          {
            id:29,
            title:"冀教版(3起点)同步课堂(四上)",
            grade:"4年级上册",
            type:"四年级上册",
            number:"共18期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dttPqH.jpg"
          },
          {
            id:30,
            title:"沪教版(3起点)同步课堂(四上)",
            grade:"4年级上册",
            type:"四年级上册",
            number:"共29期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dttFZd.jpg"
          },
          {
            id:31,
            title:"译林版(3起点)同步课堂(四上)",
            grade:"4年级上册",
            type:"四年级上册",
            number:"共14期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dttmz8.jpg"
          },
          {
            id:32,
            title:"鲁科版(3起点)同步课堂(四上)",
            grade:"4年级上册",
            type:"四年级上册",
            number:"共25期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtteRf.jpg"
          },
          {
            id:33,
            title:"北师大版(3起点)同步课堂(四上)",
            grade:"4年级上册",
            type:"四年级上册",
            number:"共13期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dttkdA.jpg"
          },
          {
            id:34,
            title:"北师大版(1起点)同步课堂(四上)",
            grade:"4年级上册",
            type:"四年级上册",
            number:"共13期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dttZJP.jpg"
          },
          {
            id:35,
            title:"北京课改版(3起点)同步课堂(四上)",
            grade:"4年级上册",
            type:"四年级上册",
            number:"共17期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dttVit.jpg"
          },
          {
            id:36,
            title:"人教版PEP(四下)同步课堂",
            grade:"4年级下册",
            type:"四年级下册",
            number:"共26期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/21/dtsU4e.jpg"
          },
          {
            id:37,
            title:"外研版(3起点)同步课堂(四下)",
            grade:"4年级下册",
            type:"四年级下册",
            number:"共11期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtsnNF.jpg"
          },
          {
            id:38,
            title:"北师大版(3起点)同步课堂(四下)",
            grade:"4年级下册",
            type:"四年级下册",
            number:"共14期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtsM9J.jpg"
          },
          {
            id:39,
            title:"译林版(3起点)同步课堂(四下)",
            grade:"4年级下册",
            type:"四年级下册",
            number:"共15期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtsBjI.jpg"
          },
          {
            id:40,
            title:"北师大版(1起点)同步课堂(四下)",
            grade:"4年级下册",
            type:"四年级下册",
            number:"共12期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dts0gA.jpg"
          },
          {
            id:41,
            title:"北京课改版(3起点)同步课堂(四下)",
            grade:"4年级下册",
            type:"四年级下册",
            number:"共12期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtsmAU.jpg"
          },
          {
            id:42,
            title:"沪教版(3起点)同步课堂(四下)",
            grade:"4年级下册",
            type:"四年级下册",
            number:"共22期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtsPpj.jpg"
          },
          {
            id:43,
            title:"冀教版(3起点)同步课堂(四下)",
            grade:"4年级下册",
            type:"四年级下册",
            number:"共20期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtsuh4.jpg"
          },
          {
            id:44,
            title:"鲁科版(3起点)同步课堂(四下)",
            grade:"4年级下册",
            type:"四年级下册",
            number:"共21期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dts1j1.jpg"
          },
          {
            id:45,
            title:"外研版(3起点)同步课堂(五上)",
            grade:"5年级上册",
            type:"五年级上册",
            number:"共13期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtWpqA.jpg"
          },
          {
            id:46,
            title:"冀教版(3起点)同步课堂(五上)",
            grade:"5年级上册",
            type:"五年级上册",
            number:"共15期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtWCVI.jpg"
          },
          {
            id:47,
            title:"鲁科版(3起点)同步课堂(五上)",
            grade:"5年级上册",
            type:"五年级上册",
            number:"共5期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtWPat.jpg"
          },
          {
            id:48,
            title:"沪教版(3起点)同步课堂(五上)",
            grade:"5年级上册",
            type:"五年级上册",
            number:"共20期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtROPK.jpg"
          },
          {
            id:49,
            title:"译林版(3起点)同步课堂(五上)",
            grade:"5年级上册",
            type:"五年级上册",
            number:"共15期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtWkPf.jpg"
          },
          {
            id:50,
            title:"北师大版(3起点)同步课堂(五上)",
            grade:"5年级上册",
            type:"五年级上册",
            number:"共16期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtWSrd.jpg"
          },
          {
            id:51,
            title:"北师大版(1起点)同步课堂(五上)",
            grade:"5年级上册",
            type:"五年级上册",
            number:"共18期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtWiIP.jpg"
          },
          {
            id:52,
            title:"人教版PEP(五下)同步课堂",
            grade:"5年级下册",
            type:"五年级下册",
            number:"共15期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/21/dtqu5Q.jpg"
          },
          {
            id:53,
            title:"外研版(3起点)同步课堂(五下)",
            grade:"5年级下册",
            type:"五年级下册",
            number:"共16期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtqZb8.jpg"
          },
          {
            id:54,
            title:"北师大版(3起点)同步课堂(五下)",
            grade:"5年级下册",
            type:"五年级下册",
            number:"共15期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtqmVS.jpg"
          },
          {
            id:55,
            title:"译林版(3起点)同步课堂(五下)",
            grade:"5年级下册",
            type:"五年级下册",
            number:"共14期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtq1vq.jpg"
          },
          {
            id:56,
            title:"北师大版(1起点)同步课堂(五下)",
            grade:"5年级下册",
            type:"五年级下册",
            number:"共14期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtql2n.jpg"
          },
          {
            id:57,
            title:"沪教版(3起点)同步课堂(五下)",
            grade:"5年级下册",
            type:"五年级下册",
            number:"共22期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtqkvt.jpg"
          },
          {
            id:58,
            title:"北京课改版(3起点)同步课堂(五下)",
            grade:"5年级下册",
            type:"五年级下册",
            number:"共19期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtqVDf.jpg"
          },
          {
            id:59,
            title:"冀教版(3起点)同步课堂(五下)",
            grade:"5年级下册",
            type:"五年级下册",
            number:"共20期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtqnUg.jpg"
          },
          {
            id:60,
            title:"鲁科版(3起点)同步课堂(五下)",
            grade:"5年级下册",
            type:"五年级下册",
            number:"共19期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/21/dtqQ8s.jpg"
          },
          {
            id:61,
            title:"人教版PEP(六上)同步课堂",
            grade:"6年级上册",
            type:"六年级上册",
            number:"共28期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dU28tP.jpg"
          },
          {
            id:62,
            title:"外研版(3起点)同步课堂(六上)",
            grade:"6年级上册",
            type:"六年级上册",
            number:"共14期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dU2uOH.jpg"
          },
          {
            id:63,
            title:"冀教版(3起点)同步课堂(六上)",
            grade:"6年级上册",
            type:"六年级上册",
            number:"共18期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dU2Q0A.jpg"
          },
          {
            id:64,
            title:"沪教版(3起点)同步课堂(六上)",
            grade:"6年级上册",
            type:"六年级上册",
            number:"共24期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dU2lTI.jpg"
          },
          {
            id:65,
            title:"北师大版(3起点)同步课堂(六上)",
            grade:"6年级上册",
            type:"六年级上册",
            number:"共14期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dU2Mmd.jpg"
          },
          {
            id:65,
            title:"译林版(3起点)同步课堂(六上)",
            grade:"6年级上册",
            type:"六年级上册",
            number:"共12期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dU2Yp8.jpg"
          },
          {
            id:66,
            title:"北师大版(1起点)同步课堂(六上)",
            grade:"6年级上册",
            type:"六年级上册",
            number:"共12期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dU2Gff.jpg"
          },
          {
            id:67,
            title:"北京课改版(3起点)同步课堂(六上)",
            grade:"6年级上册",
            type:"六年级上册",
            number:"共13期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dU23kt.jpg"
          },
          {
            id:68,
            title:"人教版PEP(六下)同步课堂",
            grade:"6年级下册",
            type:"六年级下册",
            number:"共14期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dURqP0.jpg"
          },
          {
            id:69,
            title:"外研版(3起点)同步课堂(六下)",
            grade:"6年级下册",
            type:"六年级下册",
            number:"共12期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dURTVs.jpg"
          },
          {
            id:70,
            title:"北师大版(3起点)同步课堂(六下)",
            grade:"6年级下册",
            type:"六年级下册",
            number:"共9期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dURIbj.jpg"
          },
          {
            id:71,
            title:"译林版(3起点)同步课堂(六下)",
            grade:"6年级下册",
            type:"六年级下册",
            number:"共11期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dURO2T.jpg"
          },
          {
            id:72,
            title:"北师大版(1起点)同步课堂(六下)",
            grade:"6年级下册",
            type:"六年级下册",
            number:"共11期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dURLGV.jpg"
          },
          {
            id:73,
            title:"北京课改版(3起点)同步课堂(六下)",
            grade:"6年级下册",
            type:"六年级下册",
            number:"共10期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dUR4Kg.jpg"
          },
          {
            id:74,
            title:"沪教版(3起点)同步课堂(六下)",
            grade:"6年级下册",
            type:"六年级下册",
            number:"共17期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dUR5rQ.jpg"
          },
          {
            id:75,
            title:"冀教版(3起点)同步课堂(六下)",
            grade:"6年级下册",
            type:"六年级下册",
            number:"共12期",
            price:"￥90.00",
            url:"https://s1.ax1x.com/2020/08/22/dUR7an.jpg"
          },
          {
            id:76,
            title:"自然拼音 第一阶段:26个字母发音",
            grade:"专程课题",
            type:"专程课题",
            number:"更新至26期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dUh99x.png"
          },
          {
            id:77,
            title:"巧妙记忆小学800单词",
            grade:"专题课程",
            type:"专题课程",
            number:"更新至111期",
            price:"￥79.00",
            url:"https://s1.ax1x.com/2020/08/22/dUhS41.png"
          },
          {
            id:78,
            title:"音标君的专题讲座",
            grade:"专题课程",
            type:"专题课程",
            number:"共25期",
            price:"￥79.00",
            url:"https://s1.ax1x.com/2020/08/22/dUfjHJ.jpg"
          },
          {
            id:79,
            title:"拼读难点大挑战",
            grade:"专题课程",
            type:"专题课程",
            number:"共25期",
            price:"￥50.00",
            url:"https://s1.ax1x.com/2020/08/22/dUfzNR.jpg"
          },
          {
            id:80,
            title:"开心语法街",
            grade:"专题课程",
            type:"专题课程",
            number:"共22期",
            price:"￥50.00",
            url:"https://s1.ax1x.com/2020/08/22/dUfqjU.jpg"
          },
          {
            id:81,
            title:"胖胖亲子英语",
            grade:"专题课程",
            type:"专题课程",
            number:"共115期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/dUfOuF.jpg"
          },
          {
            id:82,
            title:"阅读俱乐部",
            grade:"专题课程",
            type:"专题课程",
            number:"共20期",
            price:"￥50.00",
            url:"https://s1.ax1x.com/2020/08/22/dUfbcT.jpg"
          },
          {
            id:83,
            title:"听力直通车",
            grade:"专题课程",
            type:"专题课程",
            number:"共30期",
            price:"￥50.00",
            url:"https://s1.ax1x.com/2020/08/22/dUfH3V.jpg"
          },
          {
            id:84,
            title:"万能写作笔",
            grade:"专题课程",
            type:"专题课程",
            number:"共21期",
            price:"￥50.00",
            url:"https://s1.ax1x.com/2020/08/22/dUf790.jpg"
          },
          {
            id:85,
            title:"七彩主题会话馆",
            grade:"专题课程",
            type:"专题课程",
            number:"共16期",
            price:"￥50.00",
            url:"https://s1.ax1x.com/2020/08/22/dUfXB4.jpg"
          },
          {
            id:86,
            title:"词汇乐园",
            grade:"专题课程",
            type:"专题课程",
            number:"共30期",
            price:"￥50.00",
            url:"https://s1.ax1x.com/2020/08/22/dUfxE9.jpg"
          }
        ]
      },
      {
        id:2,
        title:'初中',
        img:"../../images/13.jpg",
        type:["全部","初一上册","初一下册","初二上册","初二下册","初三全册","专题课程"],
        product:[
          {
            id:87,
            title:"人教版7年级(上)同步课堂",
            grade:"初一上册",
            type:"初一上册",
            number:"共28期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dat0UJ.jpg"
          },
          {
            id:88,
            title:"北师大版初中同步课堂(七上)",
            grade:"初一上册",
            type:"初一上册",
            number:"更新至57期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/datwE4.jpg"
          },
          {
            id:89,
            title:"冀教版初中同步课堂(七上)",
            grade:"初一上册",
            type:"初一上册",
            number:"更新至96期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/datB59.jpg"
          },
          {
            id:90,
            title:"牛津译林版初中同步课堂(七上)",
            grade:"初一上册",
            type:"初一上册",
            number:"更新至66期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/datNuT.jpg"
          },
          {
            id:91,
            title:"仁爱版初中同步课堂(七上)",
            grade:"初一上册",
            type:"初一上册",
            number:"共71期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/datUDU.jpg"
          },
          {
            id:92,
            title:"外研版初中同步课堂(七上)",
            grade:"初一上册",
            type:"初一上册",
            number:"共57期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/databF.jpg"
          },
          {
            id:93,
            title:"鲁教版初中同步课堂(六上)",
            grade:"初一上册",
            type:"初一上册",
            number:"共64期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/datrCR.png"
          },
          {
            id:94,
            title:"鲁教版初中同步课堂(七上)",
            grade:"初一上册",
            type:"初一上册",
            number:"共64期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dats81.png"
          },
          {
            id:95,
            title:"北师大版初中同步课堂(七下)",
            grade:"初一下册",
            type:"初一下册",
            number:"更新至65期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dayLUP.jpg"
          },
          {
            id:96,
            title:"冀教版初中同步课堂(七下)",
            grade:"初一下册",
            type:"初一下册",
            number:"更新至90期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dayO4f.jpg"
          },
          {
            id:97,
            title:"牛津译林版初中同步课堂(七下)",
            grade:"初一下册",
            type:"初一下册",
            number:"更新至82期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dayqEt.jpg"
          },
          {
            id:98,
            title:"仁爱版初中同步课堂(七下)",
            grade:"初一下册",
            type:"初一下册",
            number:"共93期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dayv8S.jpg"
          },
          {
            id:99,
            title:"外研版初中同步课堂(七下)",
            grade:"初一下册",
            type:"初一下册",
            number:"共63期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dayjC8.jpg"
          },
          {
            id:100,
            title:"鲁教版初中同步课堂(六下)",
            grade:"初一下册",
            type:"初一下册",
            number:"共77期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dayzvQ.png"
          },
          {
            id:101,
            title:"鲁教版初中同步课堂(七下)",
            grade:"初一下册",
            type:"初一下册",
            number:"共86期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da69Ds.png"
          },
          {
            id:102,
            title:"人教版8年级(上)初中同步课堂",
            grade:"初二上册",
            type:"初二上册",
            number:"共44期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dacEdI.jpg"
          },
          {
            id:103,
            title:"北师大版初中同步课堂(八上)",
            grade:"初二上册",
            type:"初二上册",
            number:"更新至77期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dacmJf.jpg"
          },
          {
            id:104,
            title:"冀教版初中同步课堂(八上)",
            grade:"初二上册",
            type:"初二上册",
            number:"更新至72期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dacnW8.jpg"
          },
          {
            id:105,
            title:"牛津译林版初中同步课堂(八上)",
            grade:"初二上册",
            type:"初二上册",
            number:"更新至73期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dacAeA.jpg"
          },
          {
            id:106,
            title:"仁爱版初中同步课堂(八上)",
            grade:"初二上册",
            type:"初二上册",
            number:"共105期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/daceFP.jpg"
          },
          {
            id:107,
            title:"外研版初中同步课堂(八上)",
            grade:"初二上册",
            type:"初二上册",
            number:"共77期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dacVot.jpg"
          },
          {
            id:108,
            title:"鲁教版初中同步课堂(八上)",
            grade:"初二上册",
            type:"初二上册",
            number:"共73期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dacKSS.png"
          },
          {
            id:109,
            title:"人教版初中同步课堂(八下)",
            grade:"初二下册",
            type:"初二下册",
            number:"共90期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dacz0s.jpg"
          },
          {
            id:110,
            title:"北师大版初中同步课堂(八下)",
            grade:"初二下册",
            type:"初二下册",
            number:"更新至56期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dagS7n.jpg"
          },
          {
            id:111,
            title:"冀教版初中同步课堂(八下)",
            grade:"初二下册",
            type:"初二下册",
            number:"更新至68期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dagCt0.jpg"
          },
          {
            id:112,
            title:"牛津译林版初中同步课堂(八下)",
            grade:"初二下册",
            type:"初二下册",
            number:"更新至62期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dacjXQ.jpg"
          },
          {
            id:113,
            title:"仁爱版初中同步课堂(八下)",
            grade:"初二下册",
            type:"初二下册",
            number:"共103期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dacxmj.jpg"
          },
          {
            id:114,
            title:"外研版初中同步课堂(八下)",
            grade:"初二下册",
            type:"初二下册",
            number:"共63期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dag9kq.jpg"
          },
          {
            id:115,
            title:"鲁教版初中同步课堂(八下)",
            grade:"初二下册",
            type:"初二下册",
            number:"共51期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/dagPhV.png"
          },
          {
            id:116,
            title:"人教版初中同步课堂(九全)",
            grade:"初三全册",
            type:"初三全册",
            number:"更新至92期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5la4.jpg"
          },
          {
            id:117,
            title:"北师大版初中同步课堂(九全)",
            grade:"初三全册",
            type:"初三全册",
            number:"更新至139期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5nMV.jpg"
          },
          {
            id:118,
            title:"北师大版初中同步课堂(九全)",
            grade:"初三全册",
            type:"初三全册",
            number:"更新至139期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5nMV.jpg"
          },
          {
            id:119,
            title:"仁爱版初中同步课堂(九年级)",
            grade:"初三全册",
            type:"初三全册",
            number:"更新至139期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5KqU.jpg"
          },
          {
            id:120,
            title:"外研版初中同步课堂(九上)",
            grade:"初三全册",
            type:"初三全册",
            number:"共61期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5urT.jpg"
          },
          {
            id:121,
            title:"外研版初中同步课堂(九下)",
            grade:"初三全册",
            type:"初三全册",
            number:"共89期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },

          //未上传图片

          {
            id:122,
            title:"冀教版初中同步课堂(九全)",
            grade:"初三全册",
            type:"初三全册",
            number:"共89期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/23/dwoIKI.jpg"
          },
          {
            id:123,
            title:"牛津译林版初中同步课堂(九上)",
            grade:"初三全册",
            type:"初三全册",
            number:"共49期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwof8H.jpg"
          },
          {
            id:124,
            title:"牛津译林版初中同步课堂(九下)",
            grade:"初三全册",
            type:"初三全册",
            number:"共59期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwoh2d.jpg"
          },
          {
            id:125,
            title:"鲁教版初中同步课堂(九全)",
            grade:"初三全册",
            type:"初三全册",
            number:"共75期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwo4xA.png"
          },
          {
            id:126,
            title:"巧妙记忆初中1600单词",
            grade:"专题课程",
            type:"专题课程",
            number:"更新至72期",
            price:"￥149.00",
            url:"https://s1.ax1x.com/2020/08/23/dwTBFS.png"
          },
          {
            id:127,
            title:"初中英语语法讲解课程",
            grade:"专题课程",
            type:"专题课程",
            number:"共57期",
            price:"￥119.00",
            url:"https://s1.ax1x.com/2020/08/23/dwTDJg.jpg"
          },
          {
            id:128,
            title:"新概念英语第二册视频精讲",
            grade:"专题课程",
            type:"专题课程",
            number:"更新至380期",
            price:"￥399.00",
            url:"https://s1.ax1x.com/2020/08/23/dwTwo8.jpg"
          },
        ]
      },
      {
        id:3,
        title:'四六级',
        img:"../../images/14.jpg",
        type:["全部","四级","六级"],
        product:[
          {
            id:129,
            title:"星火英语四级高频词",
            grade:"四级",
            type:"四级",
            number:"共41期",
            price:"￥39.00",
            url:"https://s1.ax1x.com/2020/08/23/dwTLex.jpg"
          },
          {
            id:130,
            title:"星火四级无忧精品班",
            grade:"四级",
            type:"四级",
            number:"共174期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwTzfe.jpg"
          },
          {
            id:131,
            title:"英语四级写作真题讲解",
            grade:"四级",
            type:"四级",
            number:"共38期",
            price:"￥40.00",
            url:"https://s1.ax1x.com/2020/08/23/dwTvFO.jpg"
          },
          {
            id:132,
            title:"英语四级翻译真题讲解",
            grade:"四级",
            type:"四级",
            number:"共24期",
            price:"￥30.00",
            url:"https://s1.ax1x.com/2020/08/23/dwTOw6.jpg"
          },
          {
            id:133,
            title:"英语四级阅读真题讲解",
            grade:"四级",
            type:"四级",
            number:"共118期",
            price:"￥40.00",
            url:"https://s1.ax1x.com/2020/08/23/dwTxYD.jpg"
          },
          {
            id:134,
            title:"英语四级听力真题讲解",
            grade:"四级",
            type:"四级",
            number:"共120期",
            price:"￥45.00",
            url:"https://s1.ax1x.com/2020/08/23/dwTXTK.jpg"
          },
          {
            id:135,
            title:"星火式巧记速记英语四级词汇",
            grade:"四级",
            type:"四级",
            number:"共107期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dw7pSH.png"
          },

          //六级
          {
            id:136,
            title:"星火式巧记速记英语六级词汇",
            grade:"六级",
            type:"六级",
            number:"共127期",
            price:"￥39.00",
            url:"https://s1.ax1x.com/2020/08/23/dw7Rcd.jpg"
          },
          {
            id:137,
            title:"星火英语六级高频词汇",
            grade:"六级",
            type:"六级",
            number:"共31期",
            price:"￥39.00",
            url:"https://s1.ax1x.com/2020/08/23/dw75HP.jpg"
          },
          {
            id:138,
            title:"星火六级无忧精品班",
            grade:"六级",
            type:"六级",
            number:"共171期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dw7oAf.jpg"
          },
          {
            id:139,
            title:"英语六级翻译真题讲解",
            grade:"六级",
            type:"六级",
            number:"共15期",
            price:"￥20.00",
            url:"https://s1.ax1x.com/2020/08/23/dw7WjA.jpg"
          },
          {
            id:140,
            title:"英语六级阅读真题讲解",
            grade:"六级",
            type:"六级",
            number:"共51期",
            price:"￥30.00",
            url:"https://s1.ax1x.com/2020/08/23/dw7hnI.jpg"
          },
          {
            id:141,
            title:"英语六级写作真题讲解",
            grade:"六级",
            type:"六级",
            number:"共10期",
            price:"￥15.00",
            url:"https://s1.ax1x.com/2020/08/23/dw7g9e.jpg"
          },
          {
            id:142,
            title:"英语六级听力真题讲解",
            grade:"六级",
            type:"六级",
            number:"共32期",
            price:"￥30.00",
            url:"https://s1.ax1x.com/2020/08/23/dw721H.jpg"
          }
        ]
      },
      {
        id:4,
        title:'BEC',
        img:"../../images/15.jpg",
        type:["全部","BEC初级","BEC中级","BEC高级"],
        product:[
          {
            id:143,
            title:"初级商务英语听说视频课程",
            grade:"BEC初级",
            type:"BEC初级",
            number:"共63期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwqWjJ.jpg"
          },
          {
            id:144,
            title:"初级商务英语阅读视频课程",
            grade:"BEC初级",
            type:"BEC初级",
            number:"共66期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwqRc4.jpg"
          },
          {
            id:145,
            title:"初级商务英语写作视频课程",
            grade:"BEC初级",
            type:"BEC初级",
            number:"共77期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwqhu9.jpg"
          },
          {
            id:146,
            title:"中级商务英语写作视频课程",
            grade:"BEC中级",
            type:"BEC中级",
            number:"共101期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwLSEt.jpg"
          },
          {
            id:147,
            title:"中级商务英语阅读视频课程",
            grade:"BEC中级",
            type:"BEC中级",
            number:"共77期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwqvDA.jpg"
          },
          {
            id:148,
            title:"中级商务英语听说视频课程",
            grade:"BEC中级",
            type:"BEC中级",
            number:"共87期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwqxHI.jpg"
          },
          {
            id:149,
            title:"高级商务英语阅读视频课程",
            grade:"BEC高级",
            type:"BEC高级",
            number:"共79期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwL2IP.jpg"
          },
          {
            id:150,
            title:"高级商务英语写作视频课程",
            grade:"BEC高级",
            type:"BEC高级",
            number:"共54期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwLgat.jpg"
          },
          {
            id:151,
            title:"高级商务英语听说视频课程",
            grade:"BEC高级",
            type:"BEC高级",
            number:"共81期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/23/dwLcVI.jpg"
          },
        ]
      },
      {
        id:5,
        title:'考研',
        img:"../../images/16.jpg",
        type:[],
        product:[
          {
            id:152,
            title:"GMAT管卫东逻辑模考题精讲课程",
            grade:"考研",
            type:"考研",
            number:"共111期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:153,
            title:"GMAT写作题库视频课程",
            grade:"考研",
            type:"考研",
            number:"共145期",
            price:"￥89.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:154,
            title:"2018年GMAT OG句子改错题型精讲",
            grade:"考研",
            type:"考研",
            number:"共77期",
            price:"￥69.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:155,
            title:"2018年GMAT OG逻辑题型精讲",
            grade:"考研",
            type:"考研",
            number:"共72期",
            price:"￥69.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:156,
            title:"2018年GMAT OG数学(PS)题型精讲",
            grade:"考研",
            type:"考研",
            number:"共125期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:157,
            title:"2018年GMAT OG数学(DS)题型精讲",
            grade:"考研",
            type:"考研",
            number:"共95期",
            price:"￥89.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:158,
            title:"2018年GMAT OG阅读题型精讲",
            grade:"考研",
            type:"考研",
            number:"共17期",
            price:"￥29.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:159,
            title:"星火式巧记速记考研英语词汇",
            grade:"考研",
            type:"考研",
            number:"共135期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:160,
            title:"考研英语长难句精讲课程",
            grade:"考研",
            type:"考研",
            number:"共25期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:161,
            title:"考研英语写作核心词汇精讲",
            grade:"考研",
            type:"考研",
            number:"共50期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:162,
            title:"考研英语阅读精讲课程",
            grade:"考研",
            type:"考研",
            number:"共71期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
        ]
      },
      {
        id:6,
        title:'英语能力',
        img:"../../images/17.jpg",
        type:["全部","发音","词汇","基础能力","语法","听力"],
        product:[
          {
            id:163,
            title:"翻译官Holly的国际音标课",
            grade:"发音",
            type:"发音",
            number:"共51期",
            price:"￥139.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:164,
            title:"英语国际音标",
            grade:"发音",
            type:"发音",
            number:"共40期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:165,
            title:"彻底学会英语重音语调",
            grade:"发音",
            type:"发音",
            number:"共10期",
            price:"￥159.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:166,
            title:"英式发音视频课程",
            grade:"发音",
            type:"发音",
            number:"共42期",
            price:"￥39.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:167,
            title:"里昂夜读主播教你学英式音标",
            grade:"发音",
            type:"发音",
            number:"共12期",
            price:"￥179.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:168,
            title:"里昂夜读主播教你学美式音标",
            grade:"发音",
            type:"发音",
            number:"共12期",
            price:"￥179.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:169,
            title:"30天美音速成课堂",
            grade:"发音",
            type:"发音",
            number:"共26期",
            price:"￥169.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },

          //词汇

          {
            id:170,
            title:"高能词汇课",
            grade:"词汇",
            type:"词汇",
            number:"更新至22期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:171,
            title:"杨子江讲初级词汇",
            grade:"词汇",
            type:"词汇",
            number:"共2735期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:172,
            title:"孟家峰讲中级词汇",
            grade:"词汇",
            type:"词汇",
            number:"共196期",
            price:"￥139.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:173,
            title:"词根词缀速记20000单词",
            grade:"词汇",
            type:"词汇",
            number:"共30期",
            price:"￥450.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:174,
            title:"听神话故事记英语单词",
            grade:"词汇",
            type:"词汇",
            number:"共21期",
            price:"￥19.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:175,
            title:"星火单词一分钟精讲课程",
            grade:"词汇",
            type:"词汇",
            number:"共686期",
            price:"￥19.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:176,
            title:"曲根讲北美词汇",
            grade:"词汇",
            type:"词汇",
            number:"共59期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },

          //基础能力
          {
            id:177,
            title:"世界历史第一期",
            grade:"基础能力",
            type:"基础能力",
            number:"共20期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:178,
            title:"世界历史第二期",
            grade:"基础能力",
            type:"基础能力",
            number:"共20期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:179,
            title:"世界历史第三期",
            grade:"基础能力",
            type:"基础能力",
            number:"共20期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:180,
            title:"世界历史第四期",
            grade:"基础能力",
            type:"基础能力",
            number:"共20期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:181,
            title:"基础能力一级",
            grade:"基础能力",
            type:"基础能力",
            number:"共30期",
            price:"￥450.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:182,
            title:"基础能力二级",
            grade:"基础能力",
            type:"基础能力",
            number:"共30期",
            price:"￥450.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:183,
            title:"基础能力三级",
            grade:"基础能力",
            type:"基础能力",
            number:"共32期",
            price:"￥450.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:184,
            title:"基础能力四级",
            grade:"基础能力",
            type:"基础能力",
            number:"共31期",
            price:"￥450.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:185,
            title:"基础能力五级",
            grade:"基础能力",
            type:"基础能力",
            number:"共30期",
            price:"￥450.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:186,
            title:"基础能力六级",
            grade:"基础能力",
            type:"基础能力",
            number:"共30期",
            price:"￥450.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },

          //语法
          {
            id:187,
            title:"难忘的英语语法",
            grade:"语法",
            type:"语法",
            number:"更新至48期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:188,
            title:"初中英语语法讲解课程",
            grade:"语法",
            type:"语法",
            number:"共57期",
            price:"￥119.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:189,
            title:"全能语法课程",
            grade:"语法",
            type:"语法",
            number:"共31期",
            price:"￥450.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:190,
            title:"栾翔通用语法精讲课程",
            grade:"语法",
            type:"语法",
            number:"共78期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },

          //听力
          {
            id:191,
            title:"看美剧《小谢尔顿》学英语",
            grade:"听力",
            type:"听力",
            number:"共220期",
            price:"￥399.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:192,
            title:"无障碍听力第一期",
            grade:"听力",
            type:"听力",
            number:"共60期",
            price:"￥600.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
        ]
      },
      {
        id:7,
        title:'职场商务',
        img:"../../images/18.jpg",
        type:[],
        product:[
          {
            id:193,
            title:"国际新闻精讲视频",
            grade:"商务职场",
            type:"商务职场",
            number:"共277期",
            price:"￥299.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:194,
            title:"职场英语全能班",
            grade:"商务职场",
            type:"商务职场",
            number:"共59期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:195,
            title:"许岑看电影学英语",
            grade:"商务职场",
            type:"商务职场",
            number:"共29期",
            price:"￥198.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:196,
            title:"40课学透商务口语",
            grade:"商务职场",
            type:"商务职场",
            number:"共40期",
            price:"￥299.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
        ]
      },
      {
        id:8,
        title:'出国留学',
        img:"../../images/19.jpg",
        type:["全部","托福","雅思","GRE","SAT","专题课程"],
        product:[
          {
            id:197,
            title:"托福写作满分教程",
            grade:"托福",
            type:"托福",
            number:"共15期",
            price:"￥168.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:198,
            title:"托福独立写作185官方题库",
            grade:"托福",
            type:"托福",
            number:"共185期",
            price:"￥128.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:199,
            title:"托福词汇精讲课程",
            grade:"托福",
            type:"托福",
            number:"共69期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:200,
            title:"托福TPO阅读逐题精讲",
            grade:"托福",
            type:"托福",
            number:"共144期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:201,
            title:"托福TPO口语逐题精讲",
            grade:"托福",
            type:"托福",
            number:"共318期",
            price:"￥229.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:202,
            title:"托福TPO听力逐题精讲",
            grade:"托福",
            type:"托福",
            number:"共288期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:203,
            title:"托福TPO写作逐题精讲",
            grade:"托福",
            type:"托福",
            number:"共96期",
            price:"￥89.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:204,
            title:"托福官方指南(OG)逐题精讲",
            grade:"托福",
            type:"托福",
            number:"共51期",
            price:"￥69.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:205,
            title:"托福黄金口语80题精讲",
            grade:"托福",
            type:"托福",
            number:"共80期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },

          //雅思
          {
            id:206,
            title:"雅思口语首战即过",
            grade:"雅思",
            type:"雅思",
            number:"共40期",
            price:"￥399.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:207,
            title:"雅思超核心3500词逐词精讲课程",
            grade:"雅思",
            type:"雅思",
            number:"共99期",
            price:"￥499.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:208,
            title:"\"短平快\"搞定雅思口语",
            grade:"雅思",
            type:"雅思",
            number:"共30期",
            price:"￥259.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:209,
            title:"吮指原味雅思单词小课",
            grade:"雅思",
            type:"雅思",
            number:"共30期",
            price:"￥89.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:210,
            title:"吮指原味雅思单词小课",
            grade:"雅思",
            type:"雅思",
            number:"共30期",
            price:"￥89.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:211,
            title:"张生云雅思词汇课",
            grade:"雅思",
            type:"雅思",
            number:"共150期",
            price:"￥139.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:212,
            title:"雅思官方指南(EG)逐题精讲课程",
            grade:"雅思",
            type:"雅思",
            number:"共56期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:213,
            title:"雅思官方指南(OG)逐题精讲课程",
            grade:"雅思",
            type:"雅思",
            number:"共116期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:214,
            title:"雅剑桥雅思9逐题精讲课程",
            grade:"雅思",
            type:"雅思",
            number:"共44期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:215,
            title:"雅剑桥雅思10逐题精讲课程",
            grade:"雅思",
            type:"雅思",
            number:"共48期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:216,
            title:"雅剑桥雅思11逐题精讲课程",
            grade:"雅思",
            type:"雅思",
            number:"共52期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },

          //GRE
          {
            id:217,
            title:"GRE数学绿皮书视频课程",
            grade:"GRE",
            type:"GRE",
            number:"共2674期",
            price:"￥299.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:218,
            title:"GRE阅读绿皮书视频课程",
            grade:"GRE",
            type:"GRE",
            number:"共65期",
            price:"￥59.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:219,
            title:"GRE填空绿皮书视频课程",
            grade:"GRE",
            type:"GRE",
            number:"共398期",
            price:"￥229.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:220,
            title:"GRE官方150题填空逐题精讲",
            grade:"GRE",
            type:"GRE",
            number:"共82期",
            price:"￥79.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:221,
            title:"GRE官方150题数学逐题精讲",
            grade:"GRE",
            type:"GRE",
            number:"共150期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:222,
            title:"GRE官方150题阅读逐题精讲",
            grade:"GRE",
            type:"GRE",
            number:"共31期",
            price:"￥39.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:223,
            title:"GRE lssue题库逐题精讲",
            grade:"GRE",
            type:"GRE",
            number:"共121期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:224,
            title:"GRE Argument题库逐题精讲",
            grade:"GRE",
            type:"GRE",
            number:"共174期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:225,
            title:"GRE 官方指南(OG)逐题精讲",
            grade:"GRE",
            type:"GRE",
            number:"共292期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },

          //SAT
          {
            id:226,
            title:"新SAT13套数学逐题精讲",
            grade:"SAT",
            type:"SAT",
            number:"共754期",
            price:"￥159.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:227,
            title:"新SAT13套阅读逐题精讲",
            grade:"SAT",
            type:"SAT",
            number:"共65期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:228,
            title:"新SAT13套写作逐题精讲",
            grade:"SAT",
            type:"SAT",
            number:"共13期",
            price:"￥99.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:229,
            title:"新SAT13套语法逐题精讲",
            grade:"SAT",
            type:"SAT",
            number:"共52期",
            price:"￥169.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },

          //专题课程
          {
            id:230,
            title:"英语能力读写基础Level 1",
            grade:"专题课程",
            type:"专题课程",
            number:"共52期",
            price:"￥179.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:231,
            title:"英语能力读写基础Level 2",
            grade:"专题课程",
            type:"专题课程",
            number:"共47期",
            price:"￥189.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:232,
            title:"英语能力读写基础Level 3",
            grade:"专题课程",
            type:"专题课程",
            number:"共45期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:233,
            title:"英语能力听力基础Level 1",
            grade:"专题课程",
            type:"专题课程",
            number:"共70期",
            price:"￥179.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:234,
            title:"英语能力听力基础Level 2",
            grade:"专题课程",
            type:"专题课程",
            number:"共71期",
            price:"￥189.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:235,
            title:"英语能力听力基础Level 3",
            grade:"专题课程",
            type:"专题课程",
            number:"共73期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
        ]
      },
      {
        id:9,
        title:'口语',
        img:"../../images/20.jpg",
        type:[],
        product:[
          {
            id:236,
            title:"英语口语天天练",
            grade:"口语",
            type:"口语",
            number:"共365期",
            price:"￥239.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:237,
            title:"一天一句学英语",
            grade:"口语",
            type:"口语",
            number:"更新至288期",
            price:"￥180.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:238,
            title:"30天全方面搞定旅游口语",
            grade:"口语",
            type:"口语",
            number:"共30期",
            price:"￥499.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:239,
            title:"常用英语口语宝典",
            grade:"口语",
            type:"口语",
            number:"共1116期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:240,
            title:"口语通关宝典",
            grade:"口语",
            type:"口语",
            number:"共21期",
            price:"￥59.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:241,
            title:"看美剧学口语一期",
            grade:"口语",
            type:"口语",
            number:"共46期",
            price:"￥300.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:242,
            title:"零基础搞定旅游口语",
            grade:"口语",
            type:"口语",
            number:"共95期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:243,
            title:"英语口语天天练第二期",
            grade:"口语",
            type:"口语",
            number:"共164期",
            price:"￥239.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:244,
            title:"从零基础到流利21天口语课程",
            grade:"口语",
            type:"口语",
            number:"共83期",
            price:"￥129.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:245,
            title:"海外生存必备口语",
            grade:"口语",
            type:"口语",
            number:"共58期",
            price:"￥123.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
        ]
      },
      {
        id:10,
        title:'新概念',
        img:"../../images/21.jpg",
        type:[],
        product:[
          {
            id:246,
            title:"新概念英语第一册通关班",
            grade:"新概念",
            type:"新概念",
            number:"共360期",
            price:"￥559.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:247,
            title:"新概念英语第二册视频精讲",
            grade:"新概念",
            type:"新概念",
            number:"更新至380期",
            price:"￥399.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:248,
            title:"新概念英语第二册通关班",
            grade:"新概念",
            type:"新概念",
            number:"共388期",
            price:"￥499.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:249,
            title:"新概念英语第三册视频精讲",
            grade:"新概念",
            type:"新概念",
            number:"更新至253期",
            price:"￥199.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:250,
            title:"新概念英语第三册通关班",
            grade:"新概念",
            type:"新概念",
            number:"共267期",
            price:"￥499.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:251,
            title:"新概念第一册语音跟读",
            grade:"新概念",
            type:"新概念",
            number:"共106期",
            price:"￥229.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:252,
            title:"新概念第二册语音跟读",
            grade:"新概念",
            type:"新概念",
            number:"共96期",
            price:"￥229.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:253,
            title:"轻学新概念第二册第一期",
            grade:"新概念",
            type:"新概念",
            number:"共16期",
            price:"￥59.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:254,
            title:"轻学新概念第二册第二期",
            grade:"新概念",
            type:"新概念",
            number:"共16期",
            price:"￥59.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
          {
            id:255,
            title:"轻学新概念第二册第三期",
            grade:"新概念",
            type:"新概念",
            number:"共16期",
            price:"￥59.00",
            url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
          },
        ]
      }
    ],
    arr1:[
      {
        id:11,
        title:"外研版(3起点)同步课堂(三上)",
        grade:"3年级上册",
        type:"三年级上册",
        number:"共18期",
        price:"￥99.00",
        url:"https://s1.ax1x.com/2020/08/21/dtmw4J.jpg"
      },
      {
        id:130,
        title:"星火四级无忧精品班",
        grade:"四级",
        type:"四级",
        number:"共174期",
        price:"￥99.00",
        url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
      },
      {
        id:240,
        title:"口语通关宝典",
        grade:"口语",
        type:"口语",
        number:"共21期",
        price:"￥59.00",
        url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
      },
      {
        id:87,
        title:"人教版7年级(上)同步课堂",
        grade:"初一上册",
        type:"初一上册",
        number:"共28期",
        price:"￥99.00",
        url:"https://s1.ax1x.com/2020/08/22/dat0UJ.jpg"
      },
      {
        id:170,
        title:"高能词汇课",
        grade:"词汇",
        type:"词汇",
        number:"更新至22期",
        price:"￥199.00",
        url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
      },
    ],
    arr2: {
      title:"星火英语",
      type:[],
      product:[
        {
          id:129,
          title:"星火英语四级高频词",
          grade:"四级",
          type:"四级",
          number:"共41期",
          price:"￥39.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:130,
          title:"星火四级无忧精品班",
          grade:"四级",
          type:"四级",
          number:"共174期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:135,
          title:"星火式巧记速记英语四级词汇",
          grade:"四级",
          type:"四级",
          number:"共107期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:136,
          title:"星火式巧记速记英语六级词汇",
          grade:"六级",
          type:"六级",
          number:"共127期",
          price:"￥39.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:137,
          title:"星火英语六级高频词汇",
          grade:"六级",
          type:"六级",
          number:"共31期",
          price:"￥39.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:138,
          title:"星火六级无忧精品班",
          grade:"六级",
          type:"六级",
          number:"共171期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        }
      ]
    },
    arr3: {
      title:"奇文老师",
      type:[],
      product:[
        {
          id:240,
          title:"口语通关宝典",
          grade:"口语",
          type:"口语",
          number:"共21期",
          price:"￥59.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:207,
          title:"雅思超核心3500词逐词精讲课程",
          grade:"雅思",
          type:"雅思",
          number:"共99期",
          price:"￥499.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:173,
          title:"词根词缀速记20000单词",
          grade:"词汇",
          type:"词汇",
          number:"共30期",
          price:"￥450.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:253,
          title:"轻学新概念第二册第一期",
          grade:"新概念",
          type:"新概念",
          number:"共16期",
          price:"￥59.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:254,
          title:"轻学新概念第二册第二期",
          grade:"新概念",
          type:"新概念",
          number:"共16期",
          price:"￥59.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:255,
          title:"轻学新概念第二册第三期",
          grade:"新概念",
          type:"新概念",
          number:"共16期",
          price:"￥59.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:241,
          title:"看美剧学口语一期",
          grade:"口语",
          type:"口语",
          number:"共46期",
          price:"￥300.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:181,
          title:"基础能力一级",
          grade:"基础能力",
          type:"基础能力",
          number:"共30期",
          price:"￥450.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:182,
          title:"基础能力二级",
          grade:"基础能力",
          type:"基础能力",
          number:"共30期",
          price:"￥450.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:183,
          title:"基础能力三级",
          grade:"基础能力",
          type:"基础能力",
          number:"共32期",
          price:"￥450.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:184,
          title:"基础能力四级",
          grade:"基础能力",
          type:"基础能力",
          number:"共31期",
          price:"￥450.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:185,
          title:"基础能力五级",
          grade:"基础能力",
          type:"基础能力",
          number:"共30期",
          price:"￥450.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:186,
          title:"基础能力六级",
          grade:"基础能力",
          type:"基础能力",
          number:"共30期",
          price:"￥450.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:189,
          title:"全能语法课程",
          grade:"语法",
          type:"语法",
          number:"共31期",
          price:"￥450.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:192,
          title:"无障碍听力第一期",
          grade:"听力",
          type:"听力",
          number:"共60期",
          price:"￥600.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
      ]
    },
    arr4: {
      title:"剑桥雅思逐题精讲",
      type:[],
      product:[
        {
          id:212,
          title:"雅思官方指南(EG)逐题精讲课程",
          grade:"雅思",
          type:"雅思",
          number:"共56期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:213,
          title:"雅思官方指南(OG)逐题精讲课程",
          grade:"雅思",
          type:"雅思",
          number:"共116期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:214,
          title:"雅剑桥雅思9逐题精讲课程",
          grade:"雅思",
          type:"雅思",
          number:"共44期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:215,
          title:"雅剑桥雅思10逐题精讲课程",
          grade:"雅思",
          type:"雅思",
          number:"共48期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
        {
          id:216,
          title:"雅剑桥雅思11逐题精讲课程",
          grade:"雅思",
          type:"雅思",
          number:"共52期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/da5QZF.jpg"
        },
      ]
    },
    arr5: {
      title:"PEP同步课堂",
      type:[],
      product:[
        {
          id:19,
          title:"人教版PEP(三下)同步课堂",
          grade:"3年级下册",
          type:"三年级下册",
          number:"共24期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/21/dt8BCT.jpg"
        },
        {
          id:36,
          title:"人教版PEP(四下)同步课堂",
          grade:"4年级下册",
          type:"四年级下册",
          number:"共26期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/21/dtsU4e.jpg"
        },
        {
          id:52,
          title:"人教版PEP(五下)同步课堂",
          grade:"5年级下册",
          type:"五年级下册",
          number:"共15期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/21/dtqu5Q.jpg"
        },
        {
          id:52,
          title:"人教版PEP(五下)同步课堂",
          grade:"5年级下册",
          type:"五年级下册",
          number:"共15期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/21/dtqu5Q.jpg"
        },
        {
          id:61,
          title:"人教版PEP(六上)同步课堂",
          grade:"6年级上册",
          type:"六年级上册",
          number:"共28期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/dU28tP.jpg"
        },
        {
          id:68,
          title:"人教版PEP(六下)同步课堂",
          grade:"6年级下册",
          type:"六年级下册",
          number:"共14期",
          price:"￥99.00",
          url:"https://s1.ax1x.com/2020/08/22/dURqP0.jpg"
        },
      ]
    },
  },

  openNewPage:function(e){
    console.log(e.currentTarget.dataset.product);
    wx.navigateTo({
      url: '../../template/tabs/tabs?title='+e.currentTarget.dataset.title+'&&product='+JSON.stringify(e.currentTarget.dataset.product),

    })
  },
  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {

  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {

  }
})